### EXPERIENCE REQUESTS
GET http://localhost:3000/experiences
###

POST http://localhost:3000/experiences

### educations index
GET http://localhost:3000/educations

### education create
POST http://localhost:3000/educations
Content-Type: application/json

{
  "start_date": 20040101,
  "end_date": 30030101,
  "degree": "test-degree",
  "university_name": "test-university_name",
  "details": "test-details",
  "student_id": 1
}

### education show
GET http://localhost:3000/educations/1

### education update
PATCH http://localhost:3000/educations/1
Content-Type: application/json

{
  "start_date": 20050505,
  "end_date": 30050607,
  "degree": "test-degree-udpate",
  "university_name": "test-university_name-update",
  "details": "test-details-update",
  "student_id": 3
}

### education destroy
DELETE http://localhost:3000/educations/4
### Student Index
GET http://localhost:3000/students

### Student Create
POST http://localhost:3000/students
Content-Type: application/json

{
  "first_name": "Britney", 
  "last_name": "Foor",
  "email": "britney@gmail.com", 
  "phone_number": "123-456-1234",
  "bio": "bio",
  "linkedin_url": "linkedin_url",
  "twitter_handle": "twitter_handle",
  "website_url": "website_url",
  "resume_url": "resume_url",
  "github_url": "github_url",
  "photo": "photo_url",
  "password": "password"
}

### Student Show 
GET http://localhost:3000/students/1

### Student Update
PATCH http://localhost:3000/students/1 
Content-Type: application/json

{
  "first_name": "Britney", 
  "last_name": "Foor",
  "email": "britney@gmail.com", 
  "phone_number": "123-456-1234",
  "bio": "New Bio",
  "linkedin_url": "linkedin_url",
  "twitter_handle": "twitter_handle",
  "website_url": "website_url",
  "resume_url": "resume_url",
  "github_url": "github_url",
  "photo": "photo_url",
  "password": "password"
}

### Student Destroy
DELETE http://localhost:3000/students/1
